# Generated by Django 5.0.4 on 2024-04-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='apellido_materno',
            field=models.CharField(default='Pérez', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellido_paterno',
            field=models.CharField(default='López', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default=None, upload_to='candidatos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.CharField(default='Partido perr´ón', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato', verbose_name='Candidato')),
            ],
        ),
    ]
