# Generated by Django 5.0.4 on 2024-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_candidato_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
