# Generated by Django 5.0.4 on 2024-05-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_candidato_foto_alter_partido_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='logo',
        ),
    ]
